dist: trusty

language:
  - python

python:
  - 3.6

cache:
  pip: true
  directories:
    - node_modules

services:
  - postgresql

addons:
  postgresql: 9.6

before_install:
  - npm install -g npm

# command to install dependencies
install:
  - pip install codecov
  - pip install -r requirements.txt
  - npm install

before_script:
  - psql -c 'create database diana_test;' -U postgres
  - cp config/local_config_travis.py.tpl config/local_config.py
  - npm run build --Diana:app=blog
  - npm run build --Diana:app=fish
  - npm run build --Diana:app=auth
  # - npm run build --Diana:app=fun
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

# command to run tests
script: coverage run test/runtests.py

after_success:
  - codecov

matrix:
  fast_finish: true
