# Diana
version: '2'

services:
  #redis
  redis:
    image: daocloud.io/library/redis:4.0.1
    volumes:
      - ./data/redis:/data

  # postgres
  postgres:
    image: daocloud.io/library/postgres:9.6.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=diana
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  # web
  web:
    build: .
    command: gunicorn app:app -c python:config.gunicorn
    volumes:
      - .:/code
      - /etc/localtime:/etc/localtime
    environment:
      - PYTHONPATH=/code
    ports:
      - '8004:8004'
    links:
      - redis:redis
      - postgres:postgres
    restart: always
