# Diana
version: '2'

services:
  #redis
  redis:
    image: redis:4.0.10
    volumes:
      - ./data/redis:/data

  # postgres
  postgres:
    image: postgres:9.6.9
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=diana
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  # base
  web_base:
    image: iawia002/diana:latest
    volumes:
      - .:/code
    environment:
      - PYTHONPATH=/code
    restart: always

  # web
  web:
    extends:
      service: web_base
    command: gunicorn app:app -c python:config.gunicorn
    ports:
      - '8004:8004'
    links:
      - redis:redis
      - postgres:postgres

  # celery
  celery:
    extends:
      service: web_base
    command: celery -A main.celery worker --autoscale=10,1 -l INFO
    links:
      - redis:redis
      - postgres:postgres

  # beat
  beat:
    extends:
      service: web_base
    command: celery -A main.celery beat -l INFO
    links:
      - redis:redis
      - postgres:postgres
